version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - ../:/workspaces:cached
    working_dir: /workspaces
    command: sleep infinity
    ports:
      - "3000:3000"
      - "9230:9230"
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@postgres:5432/dog_checker?sslmode=disable
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dog_checker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
